# WEEK 4 ASSESSMENT

1.	Write a NumPy program to test whether none of the elements of a given array is zero.

In [5]:
import numpy as np

In [7]:
a = np.array([1,6,9,10,0,45,10])
for item in a:
    if item ==0:
        print("zero value is found")
    else:
        print(item, "is not zero")

1 is not zero
6 is not zero
9 is not zero
10 is not zero
zero value is found
45 is not zero
10 is not zero


2.	Write a NumPy program to test whether any of the elements of a given array is non-zero

In [8]:
b = np.array([1,2,0,0,3,0])
print(b)
print(np.any(b))

[1 2 0 0 3 0]
True


In [9]:
c = np.array([0,0,0,0,0,0,0,0])
print(c)
print(np.any(c))

[0 0 0 0 0 0 0 0]
False




3.	Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).


In [11]:
d = np.array([8, 10, np.nan, np.inf, 30])
print(d)
print("Test a given array element-wise for finiteness:")
print(np.isfinite(d))

[ 8. 10. nan inf 30.]
Test a given array element-wise for finiteness:
[ True  True False False  True]


4.	Write a NumPy program to test element-wise for positive or negative infinity.

In [12]:
d = np.array([8, 10, np.nan, np.inf, 30])
print(d)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(d))

[ 8. 10. nan inf 30.]
Test element-wise for positive or negative infinity:
[False False False  True False]


5.	Write a NumPy program to test element-wise for NaN of a given array.


In [13]:
e = np.array([8, 10, np.nan, np.inf, 30])
print(e)
print("Test element-wise for NaN:")
print(np.isnan(e))

[ 8. 10. nan inf 30.]
Test element-wise for NaN:
[False False  True False False]


6.	Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [14]:
f = np.array([6, 5+2j, 8+2j, 2.9, 7, 10, 11j])
print(f)

#to check complex number
print(np.iscomplex(f))

#to check for real number
print(np.isreal(f))

#to check for scalar type
print(np.isscalar(2.9))

[ 6.  +0.j  5.  +2.j  8.  +2.j  2.9 +0.j  7.  +0.j 10.  +0.j  0. +11.j]
[False  True  True False False False  True]
[ True False False  True  True  True False]
True


7.	Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [15]:
g = np.array([1e9,1e-6])
h = np.array([1.0001e12,1e-9])

#"Test if two arrays are element-wise equal within a tolerance:"
print(np.allclose(g,h))

False


8.	Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [17]:
x1 = np.array([2, 4, 6, 8])
x2 = np.array([2, 4, 8, 10])

# for greater than
print(np.greater(x1, x2))

# for greater_equal
print(np.greater_equal(x1, x2))

#for less
print(np.less(x1,x2))

# for less_equal
print(np.less_equal(x1, x2))
      

[False False False False]
[ True  True False False]
[False False  True  True]
[ True  True  True  True]


9.	Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [19]:
x1 = np.array([2, 4, 6, 8, 5, 9, 18])
x2 = np.array([2, 4, 8, 10, 7, 11, 18])

# for Comparison - equal:
print(np.equal(x1, x2))

# for Comparison - equal within a tolerance:"
print(np.allclose(x1, x2))

[ True  True False False False False  True]
False


10.	Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [20]:
y = np.array([1, 7, 13, 105])

print(y)

print("Size of the memory occupied by the said array:")
print("%d bytes" % (y.size * y.itemsize))

[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes
