# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

#### Numpy 2D Array

In [2]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [3]:
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [4]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [5]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [6]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [7]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

**Subsetting 2D NumPy Arrays**

In [8]:
a[0]

array([1, 2, 3])

In [9]:
a[0][0] # Accessing the first element from the first array

1

In [10]:
a[1][0] # Accessing the first element from the second array

4

In [12]:
a[0][1:2] # Accessing from index 1 to 2 elements from the first array

array([2])

In [15]:
a[1][1:2] # Accessing from index 1 to 2 elements from the second array

array([1])

**2D Arithmetic**

In [11]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [12]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [13]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [14]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

##### Task

1. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [17]:
print(np.allclose([2e6,1e-6], [2.00e6,1e-6]))

True


2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [20]:
a = np.array([1, 2, 5])
b = np.array([2, 2, 3])
print(a)
print(b)
#greater
print(np.greater(b, a))

[1 2 5]
[2 2 3]
[ True False False]


In [22]:
#greater_equal
print(a)
print(b)
print(np.greater_equal(a, b))


[1 2 5]
[2 2 3]
[False  True  True]


In [23]:
#less
print(a)
print(b)
print(np.less(a, b))


[1 2 5]
[2 2 3]
[ True False False]


In [24]:
print(a)
print(b)
#less_equal
print(np.less_equal(a, b))

[1 2 5]
[2 2 3]
[ True  True False]
